In [2]:
import numpy as np

a = np.array ([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized Version " + str((toc-tic)*1000)+ "ms" + "\t C is "+str(c))

c = 0

tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]

toc = time.time()
print("Witn Loop " + str((toc-tic)*1000)+ " ms" + "\t C is " +str(c))

Vectorized Version 0.8192062377929688ms	 C is 249862.979469514
Witn Loop 403.63264083862305 ms	 C is 249862.97946951678


In [13]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0) # python sum vertically 
#Horizontal is 1
print(cal)

[ 59.  239.  155.4  76.9]


In [16]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [21]:
a = np.random.randn(5) 
print(a)

[-1.02512034  1.61267538  1.51995042  1.06199762 -0.35419598]


In [20]:
print(a.shape)# rank 1 array

(5,)


In [22]:
print(a.T) # transpose

[-1.02512034  1.61267538  1.51995042  1.06199762 -0.35419598]


In [23]:
print(np.dot(a,a.T))

7.215136580351101


In [25]:
a = np.random.randn(5,1)
print(a)


[[-0.13582527]
 [-1.72589315]
 [-0.437915  ]
 [-0.32038347]
 [ 0.78949281]]


In [26]:
print(a.shape)# rank 1 array


(5, 1)


In [27]:
print(a.T) # transpose


[[-0.13582527 -1.72589315 -0.437915   -0.32038347  0.78949281]]


In [28]:
print(np.dot(a,a.T))


[[ 0.0184485   0.2344199   0.05947992  0.04351617 -0.10723307]
 [ 0.2344199   2.97870718  0.7557945   0.55294764 -1.36258024]
 [ 0.05947992  0.7557945   0.19176954  0.14030073 -0.34573074]
 [ 0.04351617  0.55294764  0.14030073  0.10264557 -0.25294045]
 [-0.10723307 -1.36258024 -0.34573074 -0.25294045  0.6232989 ]]


In [30]:
a=np.random.randn(2,3)

b=np.random.randn(2,1)

c=a+b
print(c.shape)

(2, 3)


In [31]:
a=np.random.randn(4,3)

b=np.random.randn(3,2)

c=a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [32]:
a=np.random.randn(12288,150)

b=np.random.randn(150,45)

c=np.dot(a,b)
print(c.shape)

(12288, 45)


In [33]:
a=np.random.randn(3,3)

b=np.random.randn(3,3)

c=a*b
print(c.shape)

(3, 3)
